In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [38]:
# Replace the path with the correct path for your data.
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

# Note the warning about dtypes.

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
for cols in y2015.columns: 
    print(cols)

In [0]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [0]:
# Remove two summary rows at the end that don't actually contain data.
y2015 = y2015[:-2]

In [0]:
pd.get_dummies(y2015)

In [7]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The de

array([0.97967277, 0.98050391, 0.98147752, 0.9816675 , 0.95682736,
       0.9760152 , 0.94131896, 0.98050298, 0.97995583, 0.98035909])

In [0]:
#my work starts here
#drop payment and outstanding principal related columns for drill
import regex

y2015 = y2015[y2015.columns.drop(list(y2015.filter(regex='pymnt')))]

y2015 = y2015[y2015.columns.drop(list(y2015.filter(regex='out_prncp')))]

In [0]:
for cols in y2015.columns: 
    print(cols)

In [45]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score
rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)
#nope! The variance is high and numbers are not impressive, so these columns must be too useful.

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The de

array([0.80463537, 0.73911805, 0.80199948, 0.8792477 , 0.68275944,
       0.71721681, 0.48132228, 0.66344487, 0.49761322, 0.54878165])

In [77]:
#What is the score is with *only* payment amount and outstanding principal?
stripped_df = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
stripped_df = stripped_df[['pymnt_plan','total_pymnt','total_pymnt_inv','last_pymnt_d','last_pymnt_amnt',
                          'out_prncp', 'out_prncp_inv','total_rec_prncp', 'loan_status']]


In [68]:
stripped_df.corr()
#it looks like we can even drop a few from here because of high correlation

total_pymnt  total_pymnt_inv  last_pymnt_amnt  out_prncp  \
total_pymnt         1.000000         0.999997         0.742504   0.048053   
total_pymnt_inv     0.999997         1.000000         0.742462   0.048012   
last_pymnt_amnt     0.742504         0.742462         1.000000  -0.371040   
out_prncp           0.048053         0.048012        -0.371040   1.000000   
out_prncp_inv       0.048092         0.048055        -0.371058   0.999997   
total_rec_prncp     0.964876         0.964892         0.817310  -0.135324   

                 out_prncp_inv  total_rec_prncp  
total_pymnt           0.048092         0.964876  
total_pymnt_inv       0.048055         0.964892  
last_pymnt_amnt      -0.371058         0.817310  
out_prncp             0.999997        -0.135324  
out_prncp_inv         1.000000        -0.135268  
total_rec_prncp      -0.135268         1.000000

In [0]:
stripped_df = stripped_df.drop(columns = ['total_pymnt','total_pymnt_inv','out_prncp_inv', 'total_rec_prncp'])


In [80]:
stripped_df.corr()

last_pymnt_amnt  out_prncp
last_pymnt_amnt          1.00000   -0.37104
out_prncp               -0.37104    1.00000

In [0]:
stripped_df= stripped_df[:-2]

In [82]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = stripped_df.drop('loan_status', 1)
Y = stripped_df['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)
#wow, we passed with just those few columns

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The de

array([0.95777825, 0.96141151, 0.96179146, 0.96601838, 0.95393018,
       0.96103063, 0.95893989, 0.96205087, 0.95670554, 0.96226191])